In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

## Question 1

In [2]:
# What's the version of NumPy that you installed?
np.__version__

'1.18.5'

## Question 2

In [3]:
# What's the version of Pandas?
pd.__version__

'1.2.2'

## Question 3

In [4]:
# What's the average price of BMW cars in the dataset?
df = pd.read_csv('data.csv')

In [5]:
df.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

In [6]:
avg_bmw = df[df['Make'].str.upper() == 'BMW']['MSRP'].mean()
avg_bmw

61546.76347305389

## Question 4

In [7]:
# Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [8]:
cars_after_2015 = df[df.Year >= 2015]

In [9]:
# df.info()
cars_after_2015.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [10]:
# 51

## Question 5

In [11]:
# Calculate the average "Engine HP" in the dataset.
avg = df["Engine HP"].mean()
avg

249.38607007176023

In [12]:
# Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
avg_fillna = df["Engine HP"].fillna(avg).mean()
avg_fillna

249.38607007176023

In [13]:
round(avg), round(avg_fillna)

(249.0, 249.0)

In [14]:
# Nothing changed

## Question 6

In [15]:
# Select all the "Rolls-Royce" cars from the dataset.
df_rr = df[df.Make == "Rolls-Royce"]
df_rr.shape

(31, 16)

In [16]:
# df[df['Make'].str.lower() == "rolls-royce"].shape

In [17]:
# Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
df_rr[["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [18]:
# Get the underlying NumPy array. Let's call it X
X = df_rr[["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates().values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [19]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX
XTX = X.T.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [20]:
# Invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [21]:
# What's the sum of all the elements of the result?
summ = XTX_inv.sum()
summ 

0.032212320677486125

## Question 7

In [22]:
# Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300]
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [23]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
w = XTX_inv.dot(X.T).dot(y)

In [24]:
# What's the value of the first element of w?
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [26]:
w[0]

0.19989598183188972

In [27]:
'numero_%s' % 4

'numero_4'